### ISSUE TITLE
write access required

### ISSUE THREAD

**Issue by pmarjora** [USCbiostats/Methylation-variability#5]
@gvegayon 

Hi George,
     I need to gain write access to this repo, which Emil created for our methylation work. He gave up write access when he left USC. Is that something you can set up for me? He’s made some changes that I need to merge, but I don’t seem to be able to do that at the moment, I think because I don’t have write access.
Thanks!

**Comment by gvegayon** [comment]
Granted!

**Comment by pmarjora** [comment]
Thanks!
